import type {
  EmployeePayrollReq,
  EmployeePrimaryProfile,
} from '@/types/employeeApiTypes'
import { get18YearsAgo, getTodaysDate } from './commonUtils'

export const defaultEmployeePrimaryProfile: EmployeePrimaryProfile = {
  primary: {
    id: 0,
    branch: [0, 'Select Branch'],
    code: '',
    name: '',
    prefix: 'Mr',
    doj: getTodaysDate(),
    designation: [0, 'Select Designation'],
    department: [0, 'Select Department'],
    shift: [0, 'Select Shift'],
    gender: '',
    dob: get18YearsAgo(),
    confirmationDate: getTodaysDate(),
    maritalStatus: '',
    status: '',
    guardianName: '',
    addressLine1: '',
    addressLine2: '',
    location: '',
    city: '',
    biometricNo: '',
    salaryType: '',
    aadharNo: '',
    mobilePersonal: '',
    mobileWork: '',
    bloodGroup: [0, 'Select Blood Group'],
  },
  contact: {
    presentAddress: '',
    permanentAddress: '',
    email: '',
    community: '',
    caste: '',
    religion: '',
  },
  qualifications: [
    {
      degreeOrDiplomaObtained: '',
      specialization: '',
      institutionOrUniversity: '',
      yearOfPassing: new Date().getFullYear(),
      percentageOfMarks: 0,
      additionalNotes: '',
    },
  ],
  experiences: [
    {
      organization: '',
      designation: '',
      numberOfYears: 0,
      place: '',
      additionalNotes: '',
    },
  ],
  familys: [
    {
      relation: '',
      name: '',
      age: 0,
      occupation: '',
      address: '',
      emergencyContact: '',
    },
  ],
  reference: [
    {
      name: '',
      mobile: '',
      address: '',
      notes: '',
    },
  ],
}

export const initialPayrollData: EmployeePayrollReq = {
  employeeProfileId: 0,
  month: '',
  year: new Date().getFullYear(),
  bankName: '',
  branch: '',
  accNo: '',
  ifsc: '',
  salaryPerDay: 0,
  deductionAmount: 0,
  betaAmount: 0,
  otPerHourAmount: 0,
  workHoursType: '',
  pfApplicable: true,
  pfJoinDate: getTodaysDate(),
  uanNo: '',
  pfNo: '',
  pfPercentage: 12,
  panNo: '',
  esiApplicable: true,
  esiNo: '',
  esiPercentage: 0.75,
  esiJoinDate: getTodaysDate(),
  pfSalary: 0,
  grossSalaryYearly: 0,
  grossSalaryMonthly: 0,
  basic: 0,
  hra: 0,
  da: 0,
  otherAllowance: 0,
  conveyance: 0,
  lunch: 0,
  bonus: 0,
  grossCr: 0,
  pf: 0,
  esi: 0,
  grossDr: 0,
  netPay: 0,
}
